-- ============================================
-- TOMBSTONE — DO NOT RUN THIS FILE.
--
-- This migration was never applied to production. Verified 2026-07-17 by
-- probing the live database with the service-role key: an over-budget expense,
-- an expense dated outside its month, and an expense with a negative amount
-- were all accepted. None of the triggers or constraints below exist.
--
-- Its contents have been removed rather than left in place, because running it
-- now would actively break three things:
--
-- 1. `create_default_budgets_trigger` — recreates 13 hardcoded 2024-era
--    categories (Housing 2228.00, Tithe 350.00, ...) on every new month. This
--    trigger was deliberately dropped by add_master_budgets.sql:127; the source
--    of truth for a month's categories is the user's `master_budgets` table.
--
-- 2. `validate_no_overspending` / `validate_expense_date` — the expense blocking
--    rules, removed by 20260717_remove_expense_blocking_rules.sql. An expense
--    records something that already happened and is never rejected. See that
--    migration for the full rationale.
--
-- 3. `expenses_amount_positive CHECK (amount > 0)` — would reject the negative
--    rows the Revolut CSV importer writes for Card Refunds.
--
-- The remaining constraints it declared (budgets.budget_amount >= 0,
-- income_sources.amount > 0, monthly_overviews.end_date >= start_date) are
-- already enforced in the service layer (BudgetService, IncomeSourceService,
-- MonthlyOverviewService). If database-level enforcement of those is ever
-- wanted, add them in a new migration — do not resurrect this one.
--
-- Kept as an empty file rather than deleted so that this explanation lives
-- where someone would go looking for it.
-- ============================================
